### ISSUE TITLE
Add Homebrew install script

### ISSUE THREAD

**Issue by dyba-amount** [dyba/dotfiles#4]
- [x] Update the Homebrew install script:

```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

- [x] Add Homebrew to your path by updating your `.zprofile`:

```
eval "$(/opt/homebrew/bin/brew shellenv)"
```
- [x] Optionally run different Homebrew install scripts based on which kind of Mac you're running

```
arch_name="$(uname -m)"
 
if [ "${arch_name}" = "x86_64" ]; then
    if [ "$(sysctl -in sysctl.proc_translated)" = "1" ]; then
        echo "Running on Rosetta 2"
    else
        echo "Running on native Intel"
    fi 
elif [ "${arch_name}" = "arm64" ]; then
    echo "Running on ARM"
else
    echo "Unknown architecture: ${arch_name}"
fi
```

**Comment by dyba** [comment]
Fixed here: https://github.com/dyba/dotfiles/blob/fd3cee9b9ce489cd747e793a218f7fe29d2f15ab/bin/setup_homebrew.zsh and https://github.com/dyba/dotfiles/blob/fd3cee9b9ce489cd747e793a218f7fe29d2f15ab/zsh/.zprofile
